### PR TITLE
fix various bootstrap v5 errors. drag n' dropping goes in one hand.

### LINKED ISSUE #199: moving events does not trigger update
when drag n' dropping events it does not trigger an update call. reloading the page or recollapsing the location does reset events to the old state. version [406](https://github.com/bbortt/event-planner/releases/tag/circle_406).

### PR DESCRIPTION
**Pull request by bbortt**
closes #199.

### CODE REVIEW

File: backend/src/main/java/io/github/bbortt/event/planner/backend/web/rest/EventResource.java [hunk 1]
```diff
@@ -103,7 +103,7 @@ public EventResource(EventService eventService, LocationMapper locationMapper, S
      */
     @PutMapping("/events")
     @PreAuthorize(
-        "@eventService.hasAccessToEvent(#event, \"" +
+        "@eventService.hasAccessToEvent(#event.id, \"" +
```
Comment (bbortt) [inline backend/src/main/java/io/github/bbortt/event/planner/backend/web/rest/EventResource.java:106]: this was because of a `NullPointerException` when checking access on event updates. but, actually this does not make any sense. double-check!
